### ISSUE TITLE
Blender not showing CellBlender's "Scene" or "Object" Properties

### ISSUE THREAD

**Issue by restclusion** [mcellteam/cellblender#112]
Hello,

I have an issue that is driving me crazy. I have tried installing all kind of compatible versions of cellblender, blender and mcell (3.4) as well as python, and there's the same issue.

When everything is installed correctly, I'm missing the celblender's "Scene" properties, like:
- CellBlender - Preferences
- CellBlender - Project Settings
...
- CellBlender - Define Molecules
- CellBlender - Define Regions
etc...

The ONLY droppable panel (which is empty) is the CellBlender - Examples

![isssue](https://user-images.githubusercontent.com/49172336/75032783-b28cce80-54a9-11ea-8034-00046745687b.jpg)

I don't know what to do anymore. I have installed all kind of versions, totally removed & installed again, rebooted a thousand times...

Any help would be very helpful.

Thank you.

**Comment by cnlbob** [comment]
I'm not exactly sure, but I get the impression that you may be looking for CellBlender in the wrong panel. In very early versions of CellBlender, the application's data mostly "lived" in the Property panel (as you've shown above). However, for the past few years, CellBlender is now installed in the tabbed panel which is typically on the left side of the 3D view (shown in attached image). Please let us know if that solves the problem or not.

![Tabbed_Panel](https://user-images.githubusercontent.com/3598008/75075991-e967e200-54b3-11ea-8e1d-dacd82492999.png)

**Comment by restclusion** [comment]
Thank you, you were right. I have already everything running fine.
