### ISSUE TITLE
Issue when trying to import BNGL model into CellBlender 2.93

### ISSUE THREAD

**Issue by FAnderl** [mcellteam/cellblender#121]
I am tring to import a BNG model (specifically the example model [_organelle_transport.bngl]_   from [(https://github.com/RuleWorld/BNGTutorial/blob/master/CBNGL/organelle_transport.bngl )](url) into CellBlender 2.93. 

I am using the import option _File->Import->BioNetGen/SBML model (.bngl,.xml)_ and I receive the error: 

Python: Traceback (most recent call last):
  File "/Applications/Blender-2.93-CellBlender/Blender.app/Contents/Resources/2.93/scripts/addons/cellblender/bng/__init__.py", line 43, in execute
    external_operators.filePath=findCellBlenderDirectory()+'bng{0}'.format(os.sep) + self.filepath.split(os.sep)[-1]
  File "/Applications/Blender-2.93-CellBlender/Blender.app/Contents/Resources/2.93/scripts/addons/cellblender/bng/__init__.py", line 14, in findCellBlenderDirectory
    cellblenderDir = [x for x in os.listdir(directory) if 'cellblender' in x]
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Blender-2.93-CellBlender/Blender.app/Contents/Resources/2.93/python/lib/python39.zip'

location: <unknown location>:-1

However, the import via the option _File->Import->Compartmental BioNetGen model (.bngl)_ works just fine.

**Comment by tmbartol** [comment]
Thanks for reporting this issue, Florian.  I will add a comment to organelle_transport.bngl that states that this file is a compartmental BNGL file and is intended to be imported into CellBlender using:
File->Import->Compartmental BioNetGen model (.bngl)

**Comment by FAnderl** [comment]
Thank you. 

However, I think there is an actual issue here. I receive the same error message when I am trying to import an **non**-compartmental model like e.g., LG.bngl also from the BNGL tutorial site.
