### ISSUE TITLE
Updating CellBlender Tutorials

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mcellteam/cellblender#30]
```
This will likely be an ongoing task to keep the tutorials up to date.

```

Original issue reported on code.google.com by `cnlkucze...@gmail.com` on 14 May 2013 at 4:40

**Comment by jczech** [comment]
The MCell/CellBlender tutorials now have their own repo (https://github.com/mcellteam/cellblender_tutorials) and issue tracker (https://github.com/mcellteam/cellblender_tutorials/issues). There's no reason to report issues about them here.
