### ISSUE TITLE
Counting in invalid mesh object

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mcellteam/cellblender#52]
```
When selecting an object to count in/on, the list of possible objects is taken 
from the Model Objects list, but it does not filter out those items which have 
a status associated with them (e.g. meshes with quads).
```

Original issue reported on code.google.com by `czech.ja...@gmail.com` on 14 Apr 2014 at 7:37

**Comment by jczech** [comment]
This is somewhat of a non-issue now since we auto-triangulate meshes added to the Model Objects list. However, we aren't checking for other mesh problems when adding to the Model Objects list like degenerate triangles but that should be added as a separate issue. This is being closed for now.
