### ISSUE TITLE
Update the "info tips"

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mcellteam/cellblender#63]
```
Some of the info tips (text boxes expanded upon hitting circled "i" button) 
could be updated.
```

Original issue reported on code.google.com by `czech.ja...@gmail.com` on 5 May 2014 at 3:33

**Comment by cnlbob** [comment]
I just pulled the recent MCell and I'll check the info tips against the Quick Reference Guide.

By the way, the file mcell3_qrg.pdf seems to be missing from the GitHub repository, but it was in the old BZR repository. Has it been moved?

**Comment by jczech** [comment]
Yes. It has its own repo now. https://github.com/mcellteam/mcell_qrg

**Comment by tmbartol** [comment]
I believe Bob has now updated the info tips very nicely so I'm closing this issue.
