### ISSUE TITLE
Optionally allow parameters to be displayed with engineering notation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mcellteam/cellblender#65]
```
Under "Preferences", we could optionally allow users to specify if they wanted 
parameters to be displayed with engineering notation.
```

Original issue reported on code.google.com by `czech.ja...@gmail.com` on 5 May 2014 at 3:47

**Comment by cnlbob** [comment]
This feature was added to the parameter system a long time ago, but it might not have been noted here in the issue tracker.

The Model Parameters panel has a sub-panel titled "Parameter Options". That sub-panel contains a field named "Parameter Display Format" which defaults to "%.6g". The user can specify any valid python format in that box. That format string is used to draw all general parameters and all panel parameters throughout CellBlender.
