### ISSUE TITLE
Molecule display differs for same iteration when approached from different directions

### ISSUE THREAD

**Issue by cnlbob** [mcellteam/cellblender#85]
In some (maybe all?) simulations, the molecule display looks different for the same iteration depending on the direction that time is advanced.

For example, moving forward, you may see molecules first appearing at iteration 461. However, if you then move backward by one iteration, you may see that there were molecules at iteration 460 even though they didn't appear when stepping forward in time.

**Comment by jczech** [comment]
Can you post a blend that shows this behavior?

**Comment by cnlbob** [comment]
I don't know how to post non-image files here. The data model file is only 15k (while the .blend is 3M), so that would be best to post, but I don't see a mechanism here.

It's pretty easy to recreate. Just release some molecules at a particular iteration (say 100).

As you step toward 100 from below (98, 99, 100) you'll notice that you don't see your molecules at t=100. However, if you step toward 100 from above (102, 101, 100) you'll find that your molecules are there at t=100. So it may be that stepping in one direction the index is somehow off by 1 from the same index when stepping the other direction.

**Comment by cnlbob** [comment]
In my previous post, I suggested that it might be counting improperly in different directions. But with more experimentation, the problem seems to depend on whether there were any molecules of the same type in the previous frame (where "previous frame" is the frame viewed prior to changing the frame - which could be a higher numbered frame or a lower numbered frame depending on the direction). What seems to matter isn't the direction but whether there were molecules of the same type already showing prior to the frame change. This might help diagnose the problem.

**Comment by cnlbob** [comment]
This appears to have been corrected in:
  Commit:  6aab8c4fdb34745af2fc5bf5c45835e747ed24bd
  Source ID: ba30d9b2e9254fdfc717cd6e9e5f248f524e8ebc
