### ISSUE TITLE
Create test for geometry importer

### ISSUE THREAD

**Issue by jczech** [mcellteam/cellblender#93]
The CellBlender test suite needs a test for the (swig and pyparsing) geometry importers.

**Comment by jczech** [comment]
Here is some additional information about the importers and ultimately what would be needed for this test:

The way the geometry importer normally works is that a user selects **File>Import>MCell MDL Geometry (.mdl)**. This could probably be automatically called in a test perhaps by using **bpy.ops.import_mdl_mesh.mdl()**.

Here's an example of an MDL that could be used to test this code:

    Cube POLYGON_LIST
    {
      VERTEX_LIST
      {
        [  0.1,  0.1, -0.1 ]
        [  0.1, -0.1, -0.1 ]
        [ -0.1, -0.1, -0.1 ]
        [ -0.1,  0.1, -0.1 ]
        [  0.1,  0.1,  0.1 ]
        [  0.1, -0.1,  0.1 ]
        [ -0.1, -0.1,  0.1 ]
        [ -0.1,  0.1,  0.1 ]
      }
      ELEMENT_CONNECTIONS
      {
        [ 0, 1, 2 ]
        [ 4, 7, 5 ]
        [ 0, 4, 1 ]
        [ 1, 5, 2 ]
        [ 2, 6, 7 ]
        [ 4, 0, 7 ]
        [ 3, 0, 2 ]
        [ 4, 5, 1 ]
        [ 0, 3, 7 ]
        [ 7, 6, 5 ]
        [ 3, 2, 7 ]
        [ 5, 6, 2 ]
      }
      DEFINE_SURFACE_REGIONS
      {
        left
        {
          ELEMENT_LIST = [4, 10]
        }
      }
    }

Preferably, the test would work on both the pyparsing and swig based importers. Normally, the faster swig importer is used if available (i.e. if make was run successfully). Otherwise, it will fall back to the slower (but more cross-platform friendly) pyparsing importer.

**Comment by cnlbob** [comment]
I've just submitted commit 8bcf851b6592279632cf71636475d24421ea3cb8 which includes a test of the MDL Geometry Import function.

The test generates an MDL file containing 3 geometrical objects (an "M", a "D", and an "L"). The test then calls the import_mdl_mesh.mdl operator as mentioned above to import the geometry. Three molecules are are created (M, D, and L) and released into the 3 letters.

The operator call was a bit difficult to figure out. Here's what worked:

bpy.ops.import_mdl_mesh.mdl(filepath=fn, files=[{"name":f}], directory=p, filter_glob="*.mdl", add_to_model_objects=True)

The arguments to the operator were found via a search of stackoverflow.com which led to this page:

http://stackoverflow.com/questions/25083566/import-stl-script-blender

**Comment by jczech** [comment]
I'm closing this issue after verifying that the test works correctly.
