### ISSUE TITLE
Assign "All Molecules" to Surface Property Command

### ISSUE THREAD

**Issue by jczech** [mcellteam/cellblender#94]
A user should be able to assign All Molecules, All Surface Molecules, or All Volume Molecules to a Surface Property Command (e.g. Transparent) within the context of Assign Surface Classes. Right now, it is only possible to apply specific species to a property.

**Comment by cnlbob** [comment]
I'm going to start on this one.

**Comment by cnlbob** [comment]
I *think* this has been implemented in commit a0732d1a2cf7a0b360eafbf4104b2f084a91d2a9 in the development branch. Please feel free to check it and close the issue if it looks good.

**Comment by jczech** [comment]
I've reviewed the changes in a0732d1. Everything looks good, so I'm closing this issue. :)
