### ISSUE TITLE
Page Numbers on QRG PDF

### ISSUE THREAD

**Issue by cnlbob** [mcellteam/cellblender#97]
The page numbers don't seem to be generated on the Quick Reference Guide PDF at this time.

**Comment by jczech** [comment]
Thanks for reporting this! However, it should be added to the QRG issue tracker (https://github.com/mcellteam/mcell_qrg/issues), not the CellBlender one. I'm closing this one, and I'll open a new one there.

**Comment by cnlbob** [comment]
Hi Jacob,

Actually, there's another QRG question that I have ...

There's been some new feature added to the QRG that keeps
my version of Sphinx from building it. I am only able to build
at (or around) Git commit:   f07383c .  Anything later than that,
and I get the output included below.

Thanks,
Bob



$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.1.3

Exception occurred:
   File "/usr/lib/pymodules/python2.7/sphinx/cmdline.py", line 188, in main
     warningiserror, tags)
   File "/usr/lib/pymodules/python2.7/sphinx/application.py", line 117, 
in __init__
     self.config.setup(self)
   File "/home/MCell/mcell_qrg_git/conf.py", line 248, in setup
     from mdl import MdlLexer
   File "/home/MCell/mcell_qrg_git/util/mdl.py", line 3, in <module>
     from pygments.lexer import inherit, words
ImportError: cannot import name inherit
The full traceback has been saved in /tmp/sphinx-err-fuxFsM.log, if you 
want to report the issue to the developers.
Please also report this if it was a user error, so that a better error 
message can be provided next time.
Either send bugs to the mailing list at 
<http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at 
<http://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [html] Error 1
$
